spring:
  application:
    name: parkingApp

  hibernate:
    dialect: org.hibernate.dialect.PostgresSQL9Dialect

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/parking_service_liq
    username: postgres
    password: zaq1@WSX

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

    debug: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

token:
  signing:
    key: basebasebasebasebasebasebasebasebasebasebasebasebasebasebasebase

minio:
  endpoint: http://localhost:9000
  access-key: admin12345
  secret-key: admin12345
  bucket-name: pictures

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always